### ISSUE TITLE
Problems with running the first example on Mellanox ConnectX-5

### ISSUE THREAD

**Issue by gareging** [jcxue/RDMA-Tutorial#6]
Hi,
Thanks for the great tutorial.
I have an issue when running the first example on both server and client.

================ IB Echo Server ================

************ Configuraion ************

is_server                 = true
msg_size                  = 64
num_concurr_msgs          = 1
sock_port                 = 8080

************ End of Configuraion ************

[ERROR] (setup_ib.c:184:setup_ib: errno: Cannot allocate memory) Failed to create qp
[ERROR] (main.c:39:main: errno: None) Failed to setup IB

================ Run Finished ================

**Comment by jcxue** [comment]
Thanks for the Makefile change! Hopefully that will fix the problem.

**Comment by xcheng98** [comment]
Getting the same issue. Need to reduce max_send_wr & max_recv_wr in struct qp_init_attr

**Comment by leobii** [comment]
I get the same issue, too. I've tried  reduce max_send_wr & max_recv_wr in struct qp_init_attr, but it doesn't work.
